### ISSUE TITLE
NameError: name 'reload' is not defined

### ISSUE THREAD

**Issue by Riseryn** [corus87/gkeep-neuron#2]
Hello
With Kalliope 0.6.1 i get the following error message :
```
 File "resources/neurons/gkeep/gkeep.py", line 6, in <module>
    reload(sys)  
NameError: name 'reload' is not defined
```

**Comment by Sispheor** [comment]
This line need to be removed for python 3.

**Comment by corus87** [comment]
Hi, thanks for reporting the issue, it should now be compatible with python3 and Kalliope v0.6.
