### ISSUE TITLE
update required for last kalliope version (python 3 support)

### ISSUE THREAD

**Issue by Sispheor** [corus87/gkeep-neuron#3]
The neurons seems already python 3 compliant. Only the two line that deals with the UTF8 need to be removed.

**Comment by corus87** [comment]
Done, thanks for the reminding :)

**Comment by Sispheor** [comment]
You need to update the install.yml file to precise the pip version.[ Look here for an example ](https://github.com/kalliope-project/kalliope_neuron_ambient_sound/blob/master/install.yml)
