### ISSUE TITLE
Error with password

### ISSUE THREAD

**Issue by Riseryn** [corus87/gkeep-neuron#5]
I have tis error

ERROR: Fail to execute neuron 'gkeep'. [Gnote] Login failed, maybe you set a wrong password. -> Execution skipped

Im using an application password

**Comment by Riseryn** [comment]
I hav

**Comment by corus87** [comment]
Yes, I have the same problem, I will look into this soon.

**Comment by corus87** [comment]
I have updated the neuron.
 
You can try it by removing the old neuron from your_starter_kit/resources/neurons and reinstall it with  ```kalliope install --git-url https://github.com/corus87/gkeep-neuron```

**Comment by Riseryn** [comment]
I have reinstalled and i have no problems with the password.
But a new one occured.
Should i open a new issue ?

**Comment by corus87** [comment]
Yes, open a new one then
